### ISSUE TITLE
Error !!!

### ISSUE THREAD

**Issue by andrewgf988** [xtekky/TikTok-ViewBot#123]
2023-04-08 00:16:57 INFO __main__ -> Failed to solve captcha (zefoy may have blocked you) [list index out of range]
Traceback (most recent call last):
  File "c:\Users\nguye\OneDrive\Desktop\TikTok-ViewBot-main\main.py", line 138, in <module>
    zefoy  = Zefoy(client).mainloop()
  File "c:\Users\nguye\OneDrive\Desktop\TikTok-ViewBot-main\main.py", line 77, in __init__
    this.config = load(open('config.json', 'r'))
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'

**Comment by xtekky** [comment]
updated
