### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Heyo7726** [xtekky/TikTok-ViewBot#182]
I got this error:

Traceback (most recent call last):
  File "C:\Users\notmyuserhere\OneDrive\Documents\nofname\TikTok-ViewBot-main\TikTok-ViewBot-main\v2.py", line 14, in <module>
    from webdriver_manager.chrome import ChromeDriverManager
ModuleNotFoundError: No module named 'webdriver_manager'

**Comment by Se1toku** [comment]
Run this in cmd "pip install webdriver-manager"

**Comment by Se1toku** [comment]
> I got this error:
> 
> Traceback (most recent call last): File "C:\Users\notmyuserhere\OneDrive\Documents\nofname\TikTok-ViewBot-main\TikTok-ViewBot-main\v2.py", line 14, in from webdriver_manager.chrome import ChromeDriverManager ModuleNotFoundError: No module named 'webdriver_manager'

Run this in cmd "pip install webdriver-manager"

**Comment by Heyo7726** [comment]
> > I got this error:
> > Traceback (most recent call last): File "C:\Users\notmyuserhere\OneDrive\Documents\nofname\TikTok-ViewBot-main\TikTok-ViewBot-main\v2.py", line 14, in from webdriver_manager.chrome import ChromeDriverManager ModuleNotFoundError: No module named 'webdriver_manager'
> 
> Run this in cmd "pip install webdriver-manager"

thx but now the server is busy but its fixed

**Comment by Heyo7726** [comment]
> > I got this error:
> > Traceback (most recent call last): File "C:\Users\notmyuserhere\OneDrive\Documents\nofname\TikTok-ViewBot-main\TikTok-ViewBot-main\v2.py", line 14, in from webdriver_manager.chrome import ChromeDriverManager ModuleNotFoundError: No module named 'webdriver_manager'
> 
> Run this in cmd "pip install webdriver-manager"

its back and i got another error:

Traceback (most recent call last):
  File "C:\Users\no\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\a\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\a\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\a\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\a\OneDrive\Documents\s\TikTok-ViewBot-main\v2.py", line 221, in <module>
    Zefoy().main()
  File "C:\Users\a\OneDrive\Documents\s\TikTok-ViewBot-main\v2.py", line 191, in main
    self.driver.add_cookie(self.solve())
  File "C:\Users\a\OneDrive\Documents\s\TikTok-ViewBot-main\v2.py", line 81, in solve
    captcha_answer = post(f"https://platipus9999.pythonanywhere.com/", json={'captcha': encoded_image, 'current_time': datetime.now().strftime("%H:%M:%S")}).json()["result"]
  File "C:\Users\a\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
