### ISSUE TITLE
Program crashes on captcha solver

### ISSUE THREAD

**Issue by tryformy** [xtekky/TikTok-ViewBot#184]
This issue appears to be related to the domain https://platipus9999.pythonanywhere.com/ and the fact it's no longer active and not allowing for captchas to be solved, crashing the program.

Error in question:

`Traceback (most recent call last):
File "C:\Users\no\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 971, in json
return complexjson.loads(self.text, **kwargs)
File "C:\Users\a\AppData\Local\Programs\Python\Python311\Lib\json_init_.py", line 346, in loads
return _default_decoder.decode(s)
File "C:\Users\a\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "C:\Users\a\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\a\OneDrive\Documents\s\TikTok-ViewBot-main\v2.py", line 221, in
Zefoy().main()
File "C:\Users\a\OneDrive\Documents\s\TikTok-ViewBot-main\v2.py", line 191, in main
self.driver.add_cookie(self.solve())
File "C:\Users\a\OneDrive\Documents\s\TikTok-ViewBot-main\v2.py", line 81, in solve
captcha_answer = post(f"https://platipus9999.pythonanywhere.com/", json={'captcha': encoded_image, 'current_time': datetime.now().strftime("%H:%M:%S")}).json()["result"]
File "C:\Users\a\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 975, in json
raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by RyujiXX** [comment]
found any fix?
