### ISSUE TITLE
help error 

### ISSUE THREAD

**Issue by LucasHisabf** [xtekky/TikTok-ViewBot#192]
Traceback (most recent call last):
  File "/home/dureasd/TikTok-ViewBot/test.py", line 199, in <module>
    obj = zefoy()
  File "/home/dureasd/TikTok-ViewBot/test.py", line 22, in __init__
    self.driver      = uc.Chrome()
  File "/home/dureasd/.local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "/home/dureasd/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/dureasd/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/home/dureasd/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 206, in __init__
    self.start_session(capabilities)
  File "/home/dureasd/.local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/home/dureasd/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 290, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/dureasd/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "/home/dureasd/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:38899
from chrome not reachable
Stacktrace:
#0 0x559d0bdede93 <unknown>
#1 0x559d0bae5b37 <unknown>
#2 0x559d0bad0a13 <unknown>
#3 0x559d0bb1f601 <unknown>
#4 0x559d0bb1616b <unknown>
#5 0x559d0bb5f71c <unknown>
#6 0x559d0bb52c53 <unknown>
#7 0x559d0bb23db3 <unknown>
#8 0x559d0bb2477e <unknown>
#9 0x559d0bdb37cb <unknown>
#10 0x559d0bdb77e5 <unknown>
#11 0x559d0bda10e1 <unknown>
#12 0x559d0bdb8372 <unknown>
#13 0x559d0bd851bf <unknown>
#14 0x559d0bddc488 <unknown>
#15 0x559d0bddc683 <unknown>
#16 0x559d0bded044 <unknown>
#17 0x7f15ee2e2ac3 <unknown>

**Comment by Linhvjc** [comment]
I have the same issues
