### ISSUE TITLE
Solve capcha problem

### ISSUE THREAD

**Issue by NaskaCybersec123edw** [xtekky/TikTok-ViewBot#205]
[-] Solving The Captcha
Traceback (most recent call last):
  File "C:\Users\ALH.Service\TikTok-ViewBot\v2.py", line 221, in <module>
    Zefoy().main()
  File "C:\Users\ALH.Service\TikTok-ViewBot\v2.py", line 191, in main
    self.driver.add_cookie(self.solve())
  File "C:\Users\ALH.Service\TikTok-ViewBot\v2.py", line 78, in solve
    captcha_url    = findall(r'img src="([^"]*)"', source_code)[0]
IndexError: list index out of range

**Comment by raffi1234567** [comment]
yea i also noticed it you could try to youse uc mode chromedriver from selenium base

**Comment by NaskaCybersec123edw** [comment]
??
