### ISSUE TITLE
Tread

### ISSUE THREAD

**Issue by DeviJv** [xtekky/TikTok-ViewBot#78]
Traceback (most recent call last):
  File "D:\tiktok\TikTok-ViewBot-main\main.py", line 267, in <module>
    zefoy(None).mainloop()
  File "D:\tiktok\TikTok-ViewBot-main\main.py", line 240, in mainloop
    self.__search_link(video_link); sleep(0.5)
  File "D:\tiktok\TikTok-ViewBot-main\main.py", line 208, in __search_link
    print('            ' + zefoy.sprint('*', 'sleeping -', 'for ' + Col.white + time_left +  Col.blue +' seconds'),  end="\r"); sleep(1)

**Comment by xtekky** [comment]
try restart the program, and install all independencies and latest python version
